configuration={
    "AWS_ACCESS_KEY":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "AWS_SECRET_KEY":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "OPENWEATHER_API_KEY":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
    "WAQI_API_TOKEN":"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
}


